# Generated by Django 5.2.4 on 2025-08-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Messaggio di Contatto', 'verbose_name_plural': 'Messaggi di Contatto'},
        ),
    ]
