# Generated by Django 5.2.4 on 2025-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_badge', models.CharField(default='Sistemi Embedded · Automazione · IoT', max_length=200, verbose_name='Badge del header')),
                ('header_subtitle', models.CharField(default='Posso aiutare la tua azienda a', max_length=200, verbose_name='Subtítulo del header')),
                ('header_title', models.CharField(default='Crescere e innovare', max_length=200, verbose_name='Título principal')),
                ('about_title', models.CharField(default='Chi Sono', max_length=200, verbose_name='Título de la sección')),
                ('about_subtitle', models.CharField(default='Mi chiamo Steve Cardenas Ortiz e aiuto le aziende a crescere.', max_length=200, verbose_name='Subtítulo de la sección')),
                ('about_description', models.TextField(default='Ingegnere elettronico specializzato in sistemi embedded, automazione industriale e IoT. Con oltre 8 anni di esperienza nello sviluppo di soluzioni elettroniche innovative per diverse industrie.', verbose_name='Descripción completa')),
                ('resume_button_text', models.CharField(default='Resume', max_length=50, verbose_name='Texto del botón Resume')),
                ('projects_button_text', models.CharField(default='Projects', max_length=50, verbose_name='Texto del botón Projects')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Contenido de la página de inicio',
                'verbose_name_plural': 'Contenidos de la página de inicio',
                'ordering': ['-created_at'],
            },
        ),
    ]
