# Generated by Django 5.2.4 on 2025-08-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del enlace')),
                ('url_name', models.CharField(max_length=50, verbose_name='Nombre de la URL (Django)')),
                ('display_name', models.CharField(max_length=50, verbose_name='Nombre a mostrar')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Enlace de navegación',
                'verbose_name_plural': 'Enlaces de navegación',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Steve Cardenas Ortiz', max_length=100, verbose_name='Nombre del sitio')),
                ('site_title', models.CharField(default='Steve Cardenas Ortiz - Ingegnere Elettronico', max_length=200, verbose_name='Título del sitio')),
                ('site_description', models.TextField(default='Steve Cardenas Ortiz - Ingegnere Elettronico specializzato in sistemi embedded, automazione industriale e IoT. Portfolio professionale con progetti e competenze.', verbose_name='Descripción del sitio')),
                ('profession', models.CharField(default='Ingegnere Elettronico', max_length=100, verbose_name='Profesión')),
                ('copyright_text', models.CharField(default='Copyright © Steve Cardenas Ortiz 2024', max_length=200, verbose_name='Texto de copyright')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuraciones del sitio',
                'ordering': ['-created_at'],
            },
        ),
    ]
