# Generated by Django 5.2.4 on 2025-08-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_navigation_sitesettings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='navigation',
            index=models.Index(fields=['is_active', 'order'], name='core_naviga_is_acti_e4c617_idx'),
        ),
        migrations.AddIndex(
            model_name='sitesettings',
            index=models.Index(fields=['is_active'], name='core_sitese_is_acti_6b525c_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmedia',
            index=models.Index(fields=['is_active', 'order'], name='core_social_is_acti_336300_idx'),
        ),
    ]
