# Generated by Django 5.2.4 on 2025-08-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_navigation_core_naviga_is_acti_e4c617_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homecontent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contenuto della Pagina Iniziale', 'verbose_name_plural': 'Contenuti della Pagina Iniziale'},
        ),
        migrations.AlterModelOptions(
            name='navigation',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Elemento di Navigazione', 'verbose_name_plural': 'Elementi di Navigazione'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Impostazioni del Sito', 'verbose_name_plural': 'Impostazioni del Sito'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Media'},
        ),
    ]
