# Generated by Django 5.2.4 on 2025-08-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('content', models.TextField(verbose_name='Contenuto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data di aggiornamento')),
            ],
            options={
                'verbose_name': 'Informativa sui Cookie',
                'verbose_name_plural': 'Informativa sui Cookie',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('content', models.TextField(verbose_name='Contenuto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data di aggiornamento')),
            ],
            options={
                'verbose_name': 'Informativa sulla Privacy',
                'verbose_name_plural': 'Informativa sulla Privacy',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('content', models.TextField(verbose_name='Contenuto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data di aggiornamento')),
            ],
            options={
                'verbose_name': 'Termini e Condizioni',
                'verbose_name_plural': 'Termini e Condizioni',
                'ordering': ['-updated_at'],
            },
        ),
    ]
