# Generated by Django 5.2.4 on 2025-08-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Steve Cardenas Ortiz', max_length=100)),
                ('email', models.EmailField(default='ortiz@dontsp@am', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(default='Ingegnere Elettronico', max_length=200)),
                ('summary', models.TextField(default='Ingegnere elettronico con esperienza nello sviluppo di sistemi embedded e automazione industriale.')),
                ('experience', models.TextField(default='\n    • Ingegnere Elettronico Senior - TechCorp Italia (2020-2023)\n      Sviluppo di sistemi embedded per automazione industriale\n    \n    • Ingegnere Elettronico - Automazione Roma (2018-2020)\n      Progettazione di circuiti di controllo per macchine industriali\n    \n    • Tecnico Elettronico - Elettronica Milano (2016-2018)\n      Manutenzione e riparazione di sistemi elettronici\n    ')),
                ('education', models.TextField(default='\n    • Laurea Magistrale in Ingegneria Elettronica\n      Politecnico di Milano (2014-2016)\n    \n    • Laurea Triennale in Ingegneria Elettronica\n      Università di Roma (2011-2014)\n    ')),
                ('skills', models.TextField(default='\n    • Linguaggi di programmazione: C, C++, Python, VHDL\n    • Strumenti CAD: Altium Designer, KiCad, Eagle\n    • Microcontrollori: Arduino, STM32, PIC\n    • Protocolli di comunicazione: I2C, SPI, UART, CAN\n    • Software di simulazione: Proteus, Multisim\n    • Lingue: Italiano (nativo), Inglese (fluente), Spagnolo (intermedio)\n    ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CV',
            },
        ),
    ]
