# Generated by Django 5.2.4 on 2025-08-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(verbose_name='Formazione'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(verbose_name='Esperienza Lavorativa'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(verbose_name='Competenze'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(verbose_name='Riassunto'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titolo Professionale'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data Aggiornamento'),
        ),
    ]
