# Generated by Django 5.2.4 on 2025-08-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_remove_resume_education_remove_resume_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text="Classe CSS dell'icona Bootstrap (es: bi-code-slash, bi-cpu, bi-wifi)", max_length=50, verbose_name='Icona Bootstrap'),
        ),
    ]
