# Generated by Django 5.2.4 on 2025-08-11 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_skill_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-order', '-start_date'], 'verbose_name': 'Esperienza Lavorativa', 'verbose_name_plural': 'Esperienze Lavorative'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Curriculum Vitae', 'verbose_name_plural': 'Curriculum Vitae'},
        ),
    ]
