# Generated by Django 5.2.4 on 2025-08-10 13:50

from django.db import migrations
from django.utils.text import slugify

def generate_slugs(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    
    for project in Project.objects.all():
        if not project.slug:
            base_slug = slugify(project.title)[:220]
            slug = base_slug
            counter = 1
            
            # Ensure unique slug
            while Project.objects.filter(slug=slug).exclude(id=project.id).exists():
                slug = f"{base_slug}-{counter}"[:220]
                counter += 1
            
            project.slug = slug
            project.save()

def reverse_generate_slugs(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Project.objects.all().update(slug=None)

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_slug_category_projects_ca_name_a58939_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_slugs, reverse_generate_slugs),
    ]
