# Generated by Django 5.2.4 on 2025-08-05 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_created_at_alter_resume_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Istituzione')),
                ('degree', models.CharField(max_length=200, verbose_name='Titolo di Studio')),
                ('location', models.CharField(max_length=200, verbose_name='Località')),
                ('start_date', models.DateField(verbose_name='Data Inizio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Fine')),
                ('current', models.BooleanField(default=False, verbose_name='Studi in Corso')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resume.resume', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Formazione',
                'verbose_name_plural': 'Formazioni',
                'ordering': ['-order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Azienda')),
                ('position', models.CharField(max_length=200, verbose_name='Posizione')),
                ('location', models.CharField(max_length=200, verbose_name='Località')),
                ('start_date', models.DateField(verbose_name='Data Inizio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data Fine')),
                ('current', models.BooleanField(default=False, verbose_name='Posizione Attuale')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='resume.resume', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Esperienza',
                'verbose_name_plural': 'Esperienze',
                'ordering': ['-order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome Competenza')),
                ('category', models.CharField(choices=[('programming', 'Linguaggi di Programmazione'), ('tools', 'Strumenti CAD'), ('microcontrollers', 'Microcontrollori'), ('protocols', 'Protocolli di Comunicazione'), ('software', 'Software di Simulazione'), ('languages', 'Lingue'), ('other', 'Altro')], max_length=20, verbose_name='Categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrizione')),
                ('proficiency', models.PositiveIntegerField(default=5, verbose_name='Livello di Competenza (1-10)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.resume', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Competenza',
                'verbose_name_plural': 'Competenze',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
